import localFont from "next/font/local";
import "./globals.css";
import Header from "./_components/Header";

import { ReactQueryClientProvider } from "./_components/ReactQueryClientProvider";
import Footer from "./_components/Footer";
import { Toaster } from "@/components/ui/sonner";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ReactQueryClientProvider>
      <html lang="en">
        <title>
          <link rel="icon" href="/public/logo.png" />
        </title>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <div className="md:px-20 ">
            <Header />
            {children}

            <Toaster />
          </div>
          <Footer />
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
